name: Exemple Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build et Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Vous pouvez spécifier la version de Node.js ici

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test
